name: Build EXE on Windows

on:
  push:
    branches:
      - patch-1   # ← 네 브랜치명에 맞게!
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller selenium openpyxl

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --noconsole main.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: main-exe
        path: dist/main.exe