name: Auto Build EXE
on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build EXE
      run: |
        echo 'print("Hello")' > demo.py
        pip install pyinstaller
        pyinstaller --onefile --windowed demo.py
    - uses: actions/upload-artifact@v3
      with:
        name: NaverCrawler
        path: dist/*.exe