name: Build EXE
on: 
  push:
    branches: [ main, patch-1 ]  # patch-1 추가!
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 수동 실행 가능
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        pip install pyinstaller selenium openpyxl
        pyinstaller --onefile --windowed demo.py
    - uses: actions/upload-artifact@v3
      with:
        name: NaverCrawler
        path: dist/*.exe
